# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Gems
plugins: [jekyll-paginate, jekyll-gist]

# Setup
title:            Obsolescent Gypsy
tagline:          'The never-ending journey'
description:      'An effort to document tribulations and experiences given by the greatest edifier ever: Life'
url:              http://gautamhitesh.github.io/
baseurl:          /

author:
  name:           'Hitesh Gautam'
  # url:            https://twitter.com/mdo

paginate:         5
paginate_path: "page:num"

# Custom vars
# version:          2.1.0

# github:
#   repo:           https://github.com/gautam/hyde